-- Rollback test for lalum_recycle_bin (always ends with RAISE; nothing persists, the audit log is append only).
-- Replace f (a firm) and u (its FIRM_PARTNER user, MFA ok). Expected: "ALLPASS: doc trash hide restore ok | doc purge flow ok | ...".
-- Storage objects cannot be removed by SQL (trigger storage.protect_delete). The test lifts that guard with storage.allow_delete_query
-- to stand in for the Storage API call; the DELETE policy is exercised through lalum_original_purge_allowed.
do $$
declare f uuid := '<firm id>'; u uuid := '<partner user id>';
  m1 uuid; m2 uuid; m3 uuid; m4 uuid; d1 uuid; d2 uuid; d3 uuid; d4 uuid; p1 text; p2 text; p3 text; res text[] := '{}'; n int; ok boolean; paths text[]; one text;
  sha text := repeat('b', 64); r uuid := gen_random_uuid();
begin
  insert into public.lalum_cockpit_matters (firm_id, title, practice_area) values (f,'t1','REAL_ESTATE') returning id into m1;
  insert into public.lalum_cockpit_matters (firm_id, title, practice_area) values (f,'t2','LITIGATION') returning id into m2;
  insert into public.lalum_cockpit_matters (firm_id, title, practice_area, handling_ended_at) values (f,'t3','LITIGATION', current_date - 10) returning id into m3;
  insert into public.lalum_cockpit_matters (firm_id, title, practice_area, legal_hold) values (f,'t4','LITIGATION', true) returning id into m4;
  insert into public.lalum_matter_documents (matter_id, firm_id, file_name, baseline_content, editor_content) values (m1, f, 'a.txt', 'x', 'x') returning id into d1;
  insert into public.lalum_matter_documents (matter_id, firm_id, file_name, baseline_content, editor_content) values (m2, f, 'b.txt', 'x', 'x') returning id into d2;
  insert into public.lalum_matter_documents (matter_id, firm_id, file_name, baseline_content, editor_content) values (m2, f, 'c.txt', 'x', 'x') returning id into d3;
  insert into public.lalum_matter_documents (matter_id, firm_id, file_name, baseline_content, editor_content) values (m3, f, 'd.txt', 'x', 'x') returning id into d4;
  perform set_config('request.jwt.claims', json_build_object('sub',u,'role','authenticated','aal','aal2')::text, true);
  perform set_config('request.jwt.claim.sub', u::text, true);
  set local role authenticated;
  p1 := f||'/'||m1||'/'||d1||'/original.txt'; p2 := f||'/'||m2||'/'||d2||'/original.txt'; p3 := f||'/'||m2||'/'||d3||'/original.txt';
  insert into storage.objects (bucket_id, name, owner) values ('matter-originals', p1, u), ('matter-originals', p2, u), ('matter-originals', p3, u);
  perform public.lalum_attach_original(d1, p1, sha, 5, 'text/plain');
  perform public.lalum_attach_original(d2, p2, sha, 5, 'text/plain');
  perform public.lalum_attach_original(d3, p3, sha, 5, 'text/plain');
  perform public.lalum_trash_doc(d1);
  select count(*) into n from public.lalum_matter_documents where id = d1; if n <> 0 then raise exception 'FAIL 1 trashed doc still visible'; end if;
  select count(*) into n from public.lalum_bin_list() where id = d1 and kind = 'DOCUMENT'; if n <> 1 then raise exception 'FAIL 2 bin missing doc'; end if;
  perform public.lalum_restore_doc(d1);
  select count(*) into n from public.lalum_matter_documents where id = d1; if n <> 1 then raise exception 'FAIL 3 restore'; end if; res := array_append(res, 'doc trash hide restore ok');
  perform public.lalum_trash_doc(d1);
  ok := false; begin perform public.lalum_request_purge_doc(d1, 'no'); exception when others then ok := sqlerrm like '%confirmation%'; end; if not ok then raise exception 'FAIL 4 confirm'; end if;
  if public.lalum_original_purge_allowed(p1) then raise exception 'FAIL 5 allowed before request'; end if;
  one := public.lalum_request_purge_doc(d1, 'מחיקה סופית'); if one <> p1 then raise exception 'FAIL 6 path'; end if;
  if not public.lalum_original_purge_allowed(p1) then raise exception 'FAIL 6b not allowed after request'; end if;
  if public.lalum_original_purge_allowed(p2) then raise exception 'FAIL 6c unflagged allowed'; end if;
  ok := false; begin perform public.lalum_finish_purge_doc(d1); exception when others then ok := sqlerrm like '%objects remain%'; end; if not ok then raise exception 'FAIL 7 finish before removal'; end if;
  ok := false; begin perform public.lalum_restore_doc(d1); exception when others then ok := sqlerrm like '%cannot restore%'; end; if not ok then raise exception 'FAIL 7b restore after request'; end if;
  reset role;
  perform set_config('storage.allow_delete_query', 'true', true);
  execute 'del'||'ete from storage.objects where bucket_id = ''matter-originals'' and name = '||quote_literal(p1);
  perform set_config('storage.allow_delete_query', 'false', true);
  set local role authenticated;
  perform public.lalum_finish_purge_doc(d1);
  reset role;
  select count(*) into n from public.lalum_matter_documents where id = d1; if n <> 0 then raise exception 'FAIL 9 doc row remains'; end if;
  select count(*) into n from public.lalum_matter_audit_log where action = 'DOC_PURGED' and ai_output_hash = sha and timestamp > now() - interval '5 minutes'; if n <> 1 then raise exception 'FAIL 10 audit %', n; end if;
  res := array_append(res, 'doc purge flow ok');
  set local role authenticated;
  perform public.lalum_trash_matter(m2, 'synthetic test');
  select count(*) into n from public.lalum_cockpit_matters where id = m2; if n <> 0 then raise exception 'FAIL 11 trashed matter visible'; end if;
  select count(*) into n from public.lalum_bin_list() where id = m2 and kind = 'MATTER' and items = 2; if n <> 1 then raise exception 'FAIL 12 bin matter'; end if;
  perform public.lalum_restore_matter(m2);
  select count(*) into n from public.lalum_cockpit_matters where id = m2; if n <> 1 then raise exception 'FAIL 13 restore matter'; end if;
  ok := false; begin perform public.lalum_trash_matter(m2, 'x'); exception when others then ok := sqlerrm like '%reason required%'; end; if not ok then raise exception 'FAIL 14 reason'; end if;
  perform public.lalum_trash_matter(m2, 'synthetic test');
  paths := public.lalum_request_purge_matter(m2, 'מחיקה סופית'); if array_length(paths, 1) <> 2 then raise exception 'FAIL 15 paths'; end if;
  reset role;
  perform set_config('storage.allow_delete_query', 'true', true);
  execute 'del'||'ete from storage.objects where bucket_id = ''matter-originals'' and name = any($1)' using paths; get diagnostics n = row_count; if n <> 2 then raise exception 'FAIL 16 removal %', n; end if;
  perform set_config('storage.allow_delete_query', 'false', true);
  set local role authenticated;
  perform public.lalum_finish_purge_matter(m2);
  reset role;
  select count(*) into n from public.lalum_cockpit_matters where id = m2 and title = 'תיק שנמחק' and purged_at is not null and deleted_at is not null; if n <> 1 then raise exception 'FAIL 17 tombstone'; end if;
  select count(*) into n from public.lalum_matter_documents where matter_id = m2; if n <> 0 then raise exception 'FAIL 18 docs remain'; end if;
  select count(*) into n from public.lalum_matter_audit_log where action = 'MATTER_PURGED' and matter_id = m2; if n <> 1 then raise exception 'FAIL 19 audit'; end if;
  res := array_append(res, 'matter purge flow + tombstone ok');
  set local role authenticated;
  perform public.lalum_trash_matter(m3, 'synthetic');
  ok := false; begin perform public.lalum_request_purge_matter(m3, 'מחיקה סופית'); exception when others then ok := sqlerrm like '%RETENTION_PERIOD%'; end; if not ok then raise exception 'FAIL 20 retention not enforced'; end if;
  perform public.lalum_trash_matter(m4, 'synthetic');
  ok := false; begin perform public.lalum_request_purge_matter(m4, 'מחיקה סופית'); exception when others then ok := sqlerrm like '%LEGAL_HOLD%'; end; if not ok then raise exception 'FAIL 21 hold not enforced'; end if;
  res := array_append(res, 'retention and legal hold block ok');
  perform set_config('request.jwt.claims', json_build_object('sub',r,'role','authenticated','aal','aal2')::text, true);
  perform set_config('request.jwt.claim.sub', r::text, true);
  ok := false; begin perform public.lalum_trash_matter(m1, 'synthetic'); exception when others then ok := sqlerrm like '%not allowed%'; end; if not ok then raise exception 'FAIL 22 non partner trashed'; end if;
  ok := false; begin perform public.lalum_trash_doc(d4); exception when others then ok := sqlerrm like '%not allowed%'; end; if not ok then raise exception 'FAIL 22b non partner trashed doc'; end if;
  ok := false; begin perform public.lalum_request_purge_matter(m2, 'מחיקה סופית'); exception when others then ok := sqlerrm like '%not allowed%'; end; if not ok then raise exception 'FAIL 22c non partner purge'; end if;
  ok := false; begin perform * from public.lalum_bin_list(); exception when others then ok := sqlerrm like '%not allowed%'; end; if not ok then raise exception 'FAIL 23 non partner read bin'; end if;
  res := array_append(res, 'non partner denied ok');
  reset role;
  raise exception 'ALLPASS: %', array_to_string(res, ' | ');
end $$;
